global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'sec-ops'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'app-server'
    static_configs:
      - targets: ['process.env.IP_APP:9100']

  - job_name: 'db-server'
    static_configs:
      - targets: ['process.env.IP_DB:9100']

  - job_name: 'stb-gateway'
    static_configs:
      - targets: ['process.env.IP_STB:9100']

  - job_name: 'docker-containers'
    static_configs:
      - targets: ['process.env.IP_STB:8080']
        labels:
          host: 'stb'

      - targets: ['process.env.IP_APP:8080']
        labels:
          host: 'app-server'

      - targets: ['process.env.IP_DB:8080']
        labels:
          host: 'db-server'

      - targets: ['cAdvisor:8080']
        labels:
          host: 'sec-ops'
