name: app-server

on:
  push:
    branches:
      - main
    paths:
      - 'node-apps/**'

  workflow_dispatch:

jobs:
  deploy:
    runs-on: [self-hosted, app-server]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with: 
          sparse-checkout: |
            node-apps
          sparse-checkout-cone-mode: true

      - name: Deploy with Docker Compose
        working-directory: ./node-apps
        run: |
          docker compose pull
          docker compose up -d --build  --force-recreate --remove-orphans
          echo "Deploy otomatis berhasil!"
